import { useMemo, useState } from 'react';
import { money } from '../utils/format';

// Handoff — the one page Adam (or an executor) would need on a bad day.
// Kubera-style: every account and where it lives, the people to call, where
// the documents are. Prints clean. Data stays in the user config doc.
//
// Deliberately NOT stored here: passwords, account numbers beyond the mask,
// SSNs. This is a map, not a vault — the vault is the password manager,
// and its location belongs in the notes below.

export default function Handoff({ accounts, data, updateConfig }) {
  const saved = data?.handoff || {};
  const [contacts, setContacts] = useState(saved.contacts || [
    { role: 'Partner', name: 'Adam', detail: '' },
    { role: 'Brother', name: '', detail: '' },
    { role: 'CPA', name: '', detail: '' },
    { role: 'Attorney (will/estate)', name: '', detail: '' },
    { role: 'Financial contact', name: '', detail: '' },
  ]);
  const [notes, setNotes] = useState(saved.notes || '');
  const [docsLocation, setDocsLocation] = useState(saved.docsLocation || '');
  const [dirty, setDirty] = useState(false);

  const save = () => {
    updateConfig({ handoff: { contacts, notes, docsLocation, updatedAt: new Date().toISOString() } });
    setDirty(false);
  };

  const setContact = (i, patch) => { setContacts(cs => cs.map((c, idx) => idx === i ? { ...c, ...patch } : c)); setDirty(true); };
  const addContact = () => { setContacts(cs => [...cs, { role: '', name: '', detail: '' }]); setDirty(true); };
  const removeContact = (i) => { setContacts(cs => cs.filter((_, idx) => idx !== i)); setDirty(true); };

  const byInstitution = useMemo(() => {
    const g = {};
    for (const a of accounts) {
      const key = a.institution || a.name || 'Other';
      if (!g[key]) g[key] = [];
      g[key].push(a);
    }
    for (const m of (data?.manualAccounts || [])) {
      const key = m.institution || 'Manual entries';
      if (!g[key]) g[key] = [];
      g[key].push({ ...m, manual: true });
    }
    return Object.entries(g).sort((a, b) => a[0].localeCompare(b[0]));
  }, [accounts, data?.manualAccounts]);

  return (
    <main className="max-w-5xl mx-auto p-4 space-y-6 print:text-black">
      <header className="flex items-center justify-between print:hidden">
        <div>
          <h1 className="text-2xl font-bold">Handoff</h1>
          <p className="text-slate-400 text-sm">
            What Adam or an executor needs on a bad day — accounts, people, where the documents live.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button onClick={() => window.print()} className="text-xs text-slate-400 hover:text-slate-200 border border-slate-700 rounded-lg px-3 py-1.5">
            Print / save PDF
          </button>
          <button onClick={save} className={`text-xs px-3 py-1.5 rounded-lg ${dirty ? 'bg-emerald-600 hover:bg-emerald-500 text-white' : 'text-slate-500 border border-slate-700'}`}>
            {dirty ? 'Save changes' : 'Saved'}
          </button>
        </div>
      </header>
      <div className="hidden print:block">
        <h1 className="text-2xl font-bold">Mike Dulin — financial handoff</h1>
        <p className="text-sm">Updated {new Date().toLocaleDateString()} · generated by mikesmoney</p>
      </div>

      {/* Accounts by institution */}
      <section className="bg-slate-800 border border-slate-700 rounded-xl p-4 print:bg-white print:border-slate-300">
        <h2 className="text-sm font-semibold text-slate-300 mb-3 print:text-black">Where the money is</h2>
        <div className="space-y-4">
          {byInstitution.map(([inst, accts]) => (
            <div key={inst}>
              <div className="text-xs font-semibold text-slate-400 uppercase tracking-wide mb-1 print:text-black">{inst}</div>
              <ul className="divide-y divide-slate-700/40 text-sm">
                {accts.map(a => (
                  <li key={a.id || a.name} className="py-1.5 flex items-center gap-3">
                    <span className="flex-1 truncate text-slate-300 print:text-black">
                      {a.name || a.type}{a.mask ? ` ····${a.mask}` : ''}{a.manual ? ' (manual)' : ''}
                    </span>
                    <span className="text-xs text-slate-500">{a.type}</span>
                    <span className="mono-nums w-28 text-right text-slate-200 print:text-black">{money(a.balance || 0)}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
        <p className="text-xs text-slate-500 mt-3">
          Not listed by design: TIAA requires the monthly distribution to continue for UNCC health-plan eligibility —
          whoever manages this must not stop it. Passwords live in the password manager (see notes), never here.
        </p>
      </section>

      {/* People to call */}
      <section className="bg-slate-800 border border-slate-700 rounded-xl p-4 print:bg-white print:border-slate-300">
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-sm font-semibold text-slate-300 print:text-black">People to call</h2>
          <button onClick={addContact} className="text-xs text-emerald-400 hover:text-emerald-300 print:hidden">+ Add</button>
        </div>
        <ul className="space-y-2">
          {contacts.map((c, i) => (
            <li key={i} className="grid grid-cols-12 gap-2 items-center text-sm">
              <input value={c.role} onChange={(e) => setContact(i, { role: e.target.value })} placeholder="Role"
                className="col-span-3 bg-slate-900 border border-slate-700 rounded-lg px-2 py-1 print:bg-white print:text-black" />
              <input value={c.name} onChange={(e) => setContact(i, { name: e.target.value })} placeholder="Name"
                className="col-span-3 bg-slate-900 border border-slate-700 rounded-lg px-2 py-1 print:bg-white print:text-black" />
              <input value={c.detail} onChange={(e) => setContact(i, { detail: e.target.value })} placeholder="Phone / email / firm"
                className="col-span-5 bg-slate-900 border border-slate-700 rounded-lg px-2 py-1 print:bg-white print:text-black" />
              <button onClick={() => removeContact(i)} className="col-span-1 text-slate-500 hover:text-rose-400 text-xs print:hidden">✕</button>
            </li>
          ))}
        </ul>
      </section>

      {/* Documents + notes */}
      <section className="bg-slate-800 border border-slate-700 rounded-xl p-4 print:bg-white print:border-slate-300">
        <h2 className="text-sm font-semibold text-slate-300 mb-3 print:text-black">Documents & notes</h2>
        <label className="block text-xs text-slate-400 mb-1">Where the will, POA, deeds, and password-manager recovery kit live</label>
        <input
          value={docsLocation}
          onChange={(e) => { setDocsLocation(e.target.value); setDirty(true); }}
          placeholder='e.g. "Fire safe in the study; digital copies in Dropbox/Legal; 1Password emergency kit with attorney"'
          className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm mb-3 print:bg-white print:text-black"
        />
        <label className="block text-xs text-slate-400 mb-1">Anything else they'd need to know</label>
        <textarea
          value={notes}
          onChange={(e) => { setNotes(e.target.value); setDirty(true); }}
          rows={6}
          placeholder="Rental sale status, the N. Church mortgage autopay, who Liam is, where Folio's accounts live…"
          className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm print:bg-white print:text-black"
        />
      </section>
    </main>
  );
}
